### ISSUE TITLE
Local id3 Ratings

### ISSUE THREAD

**Issue by pwd-github** [krestaino/sptnr#2]
Would it be possible to modify this to pull the ratings from the mp3 files themselves?

**Comment by krestaino** [comment]
Just so I understand, rather than getting the ratings from Spotify, you want to read the ratings from the MP3 files, and set them in Navidrome?

**Comment by uniquePWD** [comment]
Yep, exactly that.

**Comment by krestaino** [comment]
Gotcha. Yeah I don't see why not, but that's outside the scope of this project, which is to source the ratings from Spotify. I'm surprised Navidrome doesn't support something like this since it's already reading the tags. I'd open an issue over there if you want something like that.

**Comment by uniquePWD** [comment]
Thank you
